server:
  port: 9091

spring:
  application:
    name: group
  datasource:
    url: jdbc:postgresql://localhost:5432/e_journal_group_db
    username: mike
    password: password
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

info:
  group:
    microservice-name: "GROUP-MS"
    version: "v1.0.0"

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true