server:
  port: 9091

spring:
  application:
    name: group
  datasource:
    url: jdbc:h2:mem:grouptestdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
