server:
  port: 9092

spring:
  application:
    name: journal
  datasource:
    url: jdbc:postgresql://localhost:5432/e-journal-db
    username: mike
    password: password
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate

info:
  journal:
    microservice-name: "JOURNAL-MS"
    version: "v1.0.0"
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true