server:
  port:
    9090

spring:
  application:
    name: university
  config:
    activate:
      on-profile: "qa"
  datasource:
    url: jdbc:postgresql://localhost:5432/e_journal_university_text_db
    username: qa
    password: qa_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

info:
  university:
    microservice-name: "QA-UNIVERSITY-MS"
    version: "QAv1.0.0"

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/