server:
  port: 9094

spring:
  application:
    name: calendarplan
  datasource:
    url: jdbc:h2:mem:calendarplandb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

info:
  calendar-plan:
    microservice-name: "CALENDAR_PLAN_MS"
    version: "v1.0.0"

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true